//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BPQMail.rc
//
#define IDC_MYICON                      2
#define IDSENDTOMAP                     3
#define IDSelectFiles                   3
#define IDI_ICON1                       101
#define IDD_CONFIG                      102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDD_PROPPAGE_LARGE              107
#define IDC_BPQMailChat                 109
#define IDM_CONFIG                      110
#define IDM_CONSOLE                     120
#define IDM_MONITOR                     121
#define IDR_MAINFRAME                   128
#define IDD_USEREDIT                    200
#define IDD_FORWARDING                  201
#define IDD_MSGEDIT                     202
#define IDC_NODES                       501
#define IDC_USERS                       502
#define IDC_LINKS                       503
#define IDC_SYSOPMSGS                   504
#define IDC_NODES2                      505
#define IDC_FWDINT                      505
#define IDC_MAXSEND                     506
#define IDC_UTC                         506
#define IDC_MAXRECV                     507
#define IDC_LOCAL                       507
#define IDC_MAXBLOCK                    508
#define IDC_MSGS                        508
#define IDC_BBSHA                       509
#define IDC_HELD                        509
#define IDC_SMTP                        510
#define IDC_REVFWDINT                   510
#define IDC_MAXAGE                      511
#define IDC_FWDINT2                     512
#define IDC_CONTIMEOUT                  512
#define IDC_USERS2                      513
#define IDC_MSGSEM                      514
#define IDC_ALLOCSEM                    515
#define IDC_CONSEM                      517
#define COPYFROMCALL                    518
#define IDC_BBSCall                     1001
#define IDC_BaseDir                     1002
#define IDC_BBSAppl                     1003
#define IDC_BBSStreams                  1004
#define IDC_POP3Port                    1005
#define IDC_REMOVED                     1006
#define IDC_SMTPPort                    1006
#define IDC_KILLED                      1007
#define IDC_HRoute                      1007
#define IDC_LIVE                        1008
#define IDC_SYSOPCALL                   1008
#define IDC_TOTAL                       1009
#define IDC_REMOTEEMAIL                 1009
#define IDC_BIDSREMOVED                 1010
#define IDC_UIPORTS                     1010
#define IDC_NNTPPort                    1010
#define IDC_BIDSLEFT                    1011
#define IDC_AMPR                        1011
#define IDC_ENABLEUI                    1012
#define IDC_USEB2                       1013
#define IDC_REFUSEBULLS                 1013
#define IDC_CHATSEM                     1014
#define IDC_PERSONALONLY                1014
#define MAILFOR_MINS                    1014
#define IDC_SENDNEW                     1015
#define IDC_FORWARDAMPR                 1015
#define IDC_UICONFIG                    1016
#define IDC_USELOCALTIME                1016
#define IDC_DELETETORECYCLE             1017
#define IDC_CTRLZ                       1017
#define IDC_KNOWNUSERS                  1017
#define IDC_MAINTNOMAIL                 1018
#define IDC_EDIT1                       1019
#define IDC_MSGTO                       1020
#define IDC_WPVIA                       1020
#define IDC_MSGTITLE                    1021
#define IDC_MAINTSAVEREG                1021
#define IDC_MAINTTRAFFIC                1021
#define IDC_MSGBID                      1022
#define IDC_MAINTNONDELIVERY            1022
#define IDSEND                          1023
#define IDC_MAINTSAVEREG2               1023
#define IDCANCELMSG                     1024
#define BPQBASE                         1024
#define IDC_ATTACHMENTS                 1024
#define IDC_ALIAS                       1025
#define IDC_HRTEXT                      1027
#define IDC_HROUTESP                    1029
#define IDC_LASTLISTED                  1030
#define IDC_MESSAGE                     1031
#define IDSAVE                          1032
#define IDM_USERMSG                     1034
#define IDM_CHATUSERMSG                 1035
#define IDM_NEWUSERMSG                  1036
#define IDM_MSGSAVE                     1037
#define IDM_EXPERTUSERMSG               1038
#define IDC_MAPPOSITION                 1039
#define IDM_SIGNOFF                     1039
#define IDC_HOVER                       1040
#define BPQMTX                          1040
#define IDC_CLICK                       1041
#define BPQMCOM                         1041
#define IDC_MAPHELP                     1042
#define BPQCOPYMON                      1042
#define IDC_POPUPTEXT                   1043
#define BPQCOPYOUT                      1043
#define IDC_SAVEATTACHMENTS             1044
#define BPQCLEARMON                     1044
#define CONN_OUT                        1045
#define BPQCLEAROUT                     1045
#define MSGS_OUT                        1046
#define BPQBELLS                        1046
#define MSGS_IN                         1047
#define BPQCHAT                         1047
#define REJECTS_IN                      1048
#define BPQHELP                         1048
#define REJECTS_OUT                     1049
#define BPQStripLF                      1049
#define BYTES_OUT                       1050
#define BPQLogOutput                    1050
#define BYTES_IN                        1051
#define BPQLogMonitor                   1051
#define LASTCONNECT                     1052
#define BPQSendDisconnected             1052
#define CONN_IN                         1053
#define BPQFLASHONBELL                  1053
#define MONBBS                          1060
#define MONCHAT                         1061
#define MONTCP                          1062
#define IDC_CHATCALLS                   1064
#define IDC_CHATCOLOURS                 1065
#define RMS_EXPRESS_USER                1066
#define NO_WINLINKdotORG                1067
#define ALLOW_BULLS                     1068
#define RMS_SSID1                       1070
#define RMS_SSID2                       1071
#define RMS_SSID3                       1072
#define IDC_SYSTOSYSOPCALL              1073
#define IDC_DONTHOLDNEW                 1074
#define IDC_FORWARDTOBBS                1075
#define IDC_BBSTOSYSOPCALL              1076
#define IDC_NOHOMEBBS                   1077
#define IDC_NONAME                      1078
#define IDC_USERRKILLT                  1079
#define IDC_FILTERSAVE                  1080
#define IDC_OVERRIDEUNSENT              1081
#define IDC_REJBID                      1081
#define IDC_MAILFOR                     1082
#define IDC_HOLDBID                     1082
#define IDC_SENDWP                      1083
#define IDC_FILTERWPB                   1084
#define IDC_WPTYPE                      1085
#define IDC_WPTO                        1086
#define IDC_WPSAVE                      1087
#define IDC_PRINTMSG                    1088
#define IDC_EXPORT                      1089
#define IDM_PROMPTSAVE                  1090
#define IDC_RMSBULL                     1090
#define BBSUSERCHAT                     1091
#define IDC_BBSSAVE                     1500
#define ENDUSERCHAT                     1501
#define IDM_DISCONNECT                  2000
#define IDC_ChatAppl                    2001
#define IDC_ChatNodes                   2002
#define IDC_DONTCHECKFROM               2010
#define IDM_LOGGING                     2100
#define IDC_CHATSAVE                    2100
#define IDC_ISP_Gateway_Enabled         3000
#define IDC_MyMailDomain                3001
#define IDC_ISPSMTPName                 3002
#define IDC_ISPSMTPPort                 3003
#define IDC_ISPPOP3Name                 3004
#define IDC_ISPPOP3Port                 3005
#define IDC_ISPAccountName              3006
#define IDC_ISPAccountPass              3007
#define IDC_POP3Timer                   3008
#define ISP_SMTP_AUTH                   3009
#define SMTP_EHELO                      3010
#define IDC_ISPSAVE                     3100
#define IDC_FWDENABLE                   4000
#define IDC_BBS                         4001
#define IDC_CALL                        4002
#define IDC_TOCALLS                     4003
#define IDC_ATCALLS                     4004
#define IDC_TOCALLS2                    4004
#define IDC_HROUTES                     4005
#define IDC_TOCALLS3                    4005
#define IDC_REVERSE                     4006
#define IDC_TOCALLS4                    4006
#define IDC_FWDTIMES                    4008
#define IDC_FWDSAVE                     4100
#define IDC_HRHELP                      4101
#define COPYCONFIG                      4102
#define IDC_WP                          5000
#define IDC_USER                        5000
#define IDC_WPNAME                      5001
#define IDC_NAME                        5001
#define IDC_ZIP1                        5002
#define IDC_PASSWORD                    5002
#define IDC_QTH1                        5003
#define IDC_ZIP                         5003
#define IDC_QTH                         5003
#define IDC_HOMEBBS1                    5004
#define IDC_HOMEBBS                     5004
#define IDC_HOMEBBS2                    5005
#define IDC_BBSFLAG                     5005
#define IDC_QTH2                        5006
#define IDC_PMSFLAG                     5006
#define IDC_ZIP2                        5007
#define IDC_SYSOP                       5007
#define IDC_LASTSEEN                    5008
#define IDC_EXPERT                      5008
#define IDC_LASTMODIFIED                5009
#define IDC_EXCLUDED                    5009
#define IDC_TYPE                        5010
#define IDC_EMAIL                       5010
#define IDC_CHANGED                     5011
#define IDC_HOLDMAIL                    5011
#define IDC_SEEN                        5012
#define IDC_POLLRMS                     5012
#define IDC_SYSOP_IN_LM                 5013
#define IDC_UZIP                        5014
#define IDC_SYSOP_IN_LMx                5015
#define IDC_UZIP2                       5015
#define IDC_CMSPASS                     5015
#define IDC_APRSSSID                    5016
#define IDD_USERADDED_BOX               5051
#define IDD_UserEditInfo                5051
#define IDC_NTSMPS                      5060
#define IDC_APRSMFOR                    5061
#define IDC_RMSREDIRECT                 5062
#define IDC_ADDUSER                     5100
#define IDC_DELETEUSER                  5101
#define IDC_SAVEUSER                    5102
#define FILTER_FROM                     6006
#define FILTER_TO                       6007
#define FILTER_VIA                      6008
#define EMAILFROM                       6009
#define FILTER_BID                      6010
#define IDC_MSGTYPE                     6101
#define IDC_MSGSTATUS                   6102
#define IDC_SAVEMSG                     6103
#define IDC_EDITTEXT                    6104
#define IDC_SAVETOFILE                  6105
#define IDM_FORWARD_ALL                 7000
#define IDC_HOLDFROM                    7074
#define IDC_HOLDTO                      7075
#define IDC_HOLDAT                      7076
#define IDC_REJFROM                     7077
#define IDC_REJTO                       7078
#define IDC_REJAT                       7079
#define IDM_HOUSEKEEPING                9000
#define IDM_PR                          9001
#define IDM_PUR                         9002
#define IDM_PF                          9003
#define IDM_PNF                         9004
#define IDM_BF                          9005
#define IDM_BNF                         9006
#define IDM_NTSF                        9007
#define IDM_NTSU                        9008
#define IDM_LTFROM                      9009
#define IDM_LTTO                        9010
#define IDM_LTAT                        9011
#define IDM_MAINTSAVE                   9012
#define IDM_NTSD                        9013
#define IDC_MAXMSG                      9021
#define IDC_BIDLIFETIME                 9022
#define IDC_MAINTINTERVAL               9023
#define IDC_MAINTTIME                   9024
#define IDC_LOGLIFETIME                 9025
#define IDC_USERLIFETIME                9026
#define IDC_USEB1                       9876
#define IDC_READDRESSLOCAL              9877
#define IDC_READDRESSRXED               9878
#define IDC_ALLOWCOMP                   9879
#define IDC_BLOCKED                     9880
#define IDC_WARNNOROUTE                 9881
#define IDD_MAINTRESULTS                30001
#define IDD_EDITWP                      30002
#define IDD_UICONFIG                    30003
#define IDD_MSGFROMCLIPBOARD            30004
#define IDD_HRHELP                      30005
#define IDD_EDITMSGTEXT                 30006
#define IDD_UPDATECHATMAP               30007
#define IDD_CHATCOLCONFIG               30008
#define IDR_MENU1                       30010
#define IDD_RMSBULLDLG                  30011
#define IDM_USERS                       40001
#define IDM_FWD                         40002
#define IDM_MESSAGES                    40003
#define IDM_WRAPTEXT                    40004
#define IDM_WARNINPUT                   40005
#define IDM_Flash                       40006
#define IDM_CLOSEWINDOW                 40007
#define IDM_WP                          40008
#define IDC_SAVEWP                      40009
#define IDC_DELETEWP                    40010
#define IDM_DEBUG                       40011
#define IDM_LOGBBS                      40012
#define IDM_LOGTCP                      40013
#define IDM_LOGCHAT                     40014
#define ID_ACTIONS_SENDMSGFROMCLIPBOARD 40015
#define IDM_MCMONITOR                   40016
#define ID_ACTIONS_UPDATECHATMAPINFO    40017
#define IDM_EDITCHATCOLOURS             40018
#define BPQSAVEREG                      40019
#define RESCANMSGS                      40020
#define ID_HELP_ONLINEHELP              40021
#define ID_ACTIONS_SENDMESSAGE          40022
#define IDM_IMPORT                      40023
#define ID_MULTICAST                    40024
#define IDC_DEFAULTNOWINLINK            41001
#define IDC_MULTIP                      41002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        30012
#define _APS_NEXT_COMMAND_VALUE         40027
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
